import type { Equal } from '../../types/equal.ts'
import type { Expect } from '../../types/expect.ts'

/**
 * An object of all the currencies supported by Razorpay.
 *
 * @see https://razorpay.com/docs/payments/international-payments#supported-currencies
 */
export const RAZORPAY_CURRENCIES = {
  AED: { code: 'AED', name: 'United Arab Emirates Dirham', exponent: 2 },
  ALL: { code: 'ALL', name: 'Albanian Lek', exponent: 2 },
  AMD: { code: 'AMD', name: 'Armenian Dram', exponent: 2 },
  AUD: { code: 'AUD', name: 'Australian Dollar', exponent: 2 },
  AWG: { code: 'AWG', name: 'Aruban Florin', exponent: 2 },
  AZN: { code: 'AZN', name: 'Azerbaijan Manat', exponent: 2 },
  BAM: { code: 'BAM', name: 'Convertible Mark', exponent: 2 },
  BBD: { code: 'BBD', name: 'Barbadian Dollar', exponent: 2 },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', exponent: 2 },
  BGN: { code: 'BGN', name: 'Bulgarian Lev', exponent: 2 },
  BHD: { code: 'BHD', name: 'Bahraini Dinar', exponent: 3 },
  BIF: { code: 'BIF', name: 'Burundi franc', exponent: 0 },
  BMD: { code: 'BMD', name: 'Bermudian Dollar', exponent: 2 },
  BND: { code: 'BND', name: 'Brunei Dollar', exponent: 2 },
  BOB: { code: 'BOB', name: 'Bolivian Boliviano', exponent: 2 },
  BRL: { code: 'BRL', name: 'Brazilian Real', exponent: 2 },
  BSD: { code: 'BSD', name: 'Bahamian Dollar', exponent: 2 },
  BTN: { code: 'BTN', name: 'Bhutanese Ngultrum', exponent: 2 },
  BWP: { code: 'BWP', name: 'Botswana Pula', exponent: 2 },
  BZD: { code: 'BZD', name: 'Belize Dollar', exponent: 2 },
  CAD: { code: 'CAD', name: 'Canadian Dollar', exponent: 2 },
  CHF: { code: 'CHF', name: 'Swiss Franc', exponent: 2 },
  CLP: { code: 'CLP', name: 'Chilean Peso', exponent: 0 },
  CNY: { code: 'CNY', name: 'Chinese Yuan Renminbi', exponent: 2 },
  COP: { code: 'COP', name: 'Colombian Peso', exponent: 2 },
  CRC: { code: 'CRC', name: 'Costa Rican Colon', exponent: 2 },
  CUP: { code: 'CUP', name: 'Cuban Peso', exponent: 2 },
  CVE: { code: 'CVE', name: 'Cabo Verde Escudo', exponent: 2 },
  CZK: { code: 'CZK', name: 'Czech Koruna', exponent: 2 },
  DJF: { code: 'DJF', name: 'Djibouti franc', exponent: 0 },
  DKK: { code: 'DKK', name: 'Danish Krone', exponent: 2 },
  DOP: { code: 'DOP', name: 'Dominican Peso', exponent: 2 },
  DZD: { code: 'DZD', name: 'Algerian Dinar', exponent: 2 },
  EGP: { code: 'EGP', name: 'Egyptian Pound', exponent: 2 },
  ETB: { code: 'ETB', name: 'Ethiopian Birr', exponent: 2 },
  EUR: { code: 'EUR', name: 'Euro', exponent: 2 },
  FJD: { code: 'FJD', name: 'Fijian Dollar', exponent: 2 },
  GBP: { code: 'GBP', name: 'Pound Sterling', exponent: 2 },
  GHS: { code: 'GHS', name: 'Ghanaian Cedi', exponent: 2 },
  GIP: { code: 'GIP', name: 'Gibraltar Pound', exponent: 2 },
  GMD: { code: 'GMD', name: 'Gambian Dalasi', exponent: 2 },
  GNF: { code: 'GNF', name: 'Guinean franc', exponent: 0 },
  GTQ: { code: 'GTQ', name: 'Guatemalan Quetzal', exponent: 2 },
  GYD: { code: 'GYD', name: 'Guyanese Dollar', exponent: 2 },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', exponent: 2 },
  HNL: { code: 'HNL', name: 'Honduran Lempira', exponent: 2 },
  HRK: { code: 'HRK', name: 'Croatian Kuna', exponent: 2 },
  HTG: { code: 'HTG', name: 'Haitian Gourde', exponent: 2 },
  HUF: { code: 'HUF', name: 'Hungarian Forint', exponent: 2 },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', exponent: 2 },
  ILS: { code: 'ILS', name: 'Israeli New Shekel', exponent: 2 },
  INR: { code: 'INR', name: 'Indian Rupee', exponent: 2 },
  IQD: { code: 'IQD', name: 'Iraqi Dinar', exponent: 3 },
  ISK: { code: 'ISK', name: 'Iceland Krona', exponent: 0 },
  JMD: { code: 'JMD', name: 'Jamaican Dollar', exponent: 2 },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', exponent: 3 },
  JPY: { code: 'JPY', name: 'Japanese Yen', exponent: 0 },
  KES: { code: 'KES', name: 'Kenyan Shilling', exponent: 2 },
  KGS: { code: 'KGS', name: 'Kyrgyzstani Som', exponent: 2 },
  KHR: { code: 'KHR', name: 'Cambodian Riel', exponent: 2 },
  KMF: { code: 'KMF', name: 'Comorian Franc', exponent: 0 },
  KRW: { code: 'KRW', name: 'Korean Won', exponent: 0 },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', exponent: 3 },
  KYD: { code: 'KYD', name: 'Cayman Islands Dollar', exponent: 2 },
  KZT: { code: 'KZT', name: 'Kazakhstani Tenge', exponent: 2 },
  LAK: { code: 'LAK', name: 'Lao Kip', exponent: 2 },
  LKR: { code: 'LKR', name: 'Sri Lankan Rupee', exponent: 2 },
  LRD: { code: 'LRD', name: 'Liberian Dollar', exponent: 2 },
  LSL: { code: 'LSL', name: 'Lesotho Loti', exponent: 2 },
  MAD: { code: 'MAD', name: 'Moroccan Dirham', exponent: 2 },
  MDL: { code: 'MDL', name: 'Moldovan Leu', exponent: 2 },
  MGA: { code: 'MGA', name: 'Malagasy Ariary', exponent: 2 },
  MKD: { code: 'MKD', name: 'Macedonian Denar', exponent: 2 },
  MMK: { code: 'MMK', name: 'Myanmar Kyat', exponent: 2 },
  MNT: { code: 'MNT', name: 'Mongolian Tugrik', exponent: 2 },
  MOP: { code: 'MOP', name: 'Macanese Pataca', exponent: 2 },
  MUR: { code: 'MUR', name: 'Mauritian Rupee', exponent: 2 },
  MVR: { code: 'MVR', name: 'Maldivian Rufiyaa', exponent: 2 },
  MWK: { code: 'MWK', name: 'Malawian Kwacha', exponent: 2 },
  MXN: { code: 'MXN', name: 'Mexican Peso', exponent: 2 },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', exponent: 2 },
  MZN: { code: 'MZN', name: 'Mozambique Metical', exponent: 2 },
  NAD: { code: 'NAD', name: 'Namibian Dollar', exponent: 2 },
  NGN: { code: 'NGN', name: 'Nigerian Naira', exponent: 2 },
  NIO: { code: 'NIO', name: 'Nicaraguan Cordoba', exponent: 2 },
  NOK: { code: 'NOK', name: 'Norwegian Krone', exponent: 2 },
  NPR: { code: 'NPR', name: 'Nepalese Rupee', exponent: 2 },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', exponent: 2 },
  OMR: { code: 'OMR', name: 'Omani Rial', exponent: 3 },
  PEN: { code: 'PEN', name: 'Peruvian Sol', exponent: 2 },
  PGK: { code: 'PGK', name: 'Papua New Guinean Kina', exponent: 2 },
  PHP: { code: 'PHP', name: 'Philippine Peso', exponent: 2 },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', exponent: 2 },
  PLN: { code: 'PLN', name: 'Polish Zloty', exponent: 2 },
  PYG: { code: 'PYG', name: 'Paraguayan Guarani', exponent: 0 },
  QAR: { code: 'QAR', name: 'Qatari Riyal', exponent: 2 },
  RON: { code: 'RON', name: 'Romanian Leu', exponent: 2 },
  RSD: { code: 'RSD', name: 'Serbian Dinar', exponent: 2 },
  RUB: { code: 'RUB', name: 'Russian Ruble', exponent: 2 },
  RWF: { code: 'RWF', name: 'Rwanda franc', exponent: 0 },
  SAR: { code: 'SAR', name: 'Saudi Arabian Riyal', exponent: 2 },
  SCR: { code: 'SCR', name: 'Seychellois Rupee', exponent: 2 },
  SEK: { code: 'SEK', name: 'Swedish Krona', exponent: 2 },
  SGD: { code: 'SGD', name: 'Singapore Dollar', exponent: 2 },
  SLL: { code: 'SLL', name: 'Sierra Leonean Leone', exponent: 2 },
  SOS: { code: 'SOS', name: 'Somali Shilling', exponent: 2 },
  SVC: { code: 'SVC', name: 'Salvadoran Colón', exponent: 2 },
  SZL: { code: 'SZL', name: 'Swazi Lilangeni', exponent: 2 },
  THB: { code: 'THB', name: 'Thai Baht', exponent: 2 },
  TND: { code: 'TND', name: 'Tunisian Dinar', exponent: 3 },
  TRY: { code: 'TRY', name: 'Turkish Lira', exponent: 2 },
  TTD: { code: 'TTD', name: 'Trinidad And Tobago Dollar', exponent: 2 },
  TWD: { code: 'TWD', name: 'New Taiwan Dollar', exponent: 2 },
  TZS: { code: 'TZS', name: 'Tanzanian Shilling', exponent: 2 },
  UAH: { code: 'UAH', name: 'Ukrainian Hryvnia', exponent: 2 },
  UGX: { code: 'UGX', name: 'Uganda Shilling', exponent: 0 },
  USD: { code: 'USD', name: 'United States Dollar', exponent: 2 },
  UYU: { code: 'UYU', name: 'Uruguayan Peso', exponent: 2 },
  UZS: { code: 'UZS', name: "Uzbekistani So'm", exponent: 2 },
  VND: { code: 'VND', name: 'Vietnamese Dong', exponent: 0 },
  VUV: { code: 'VUV', name: 'Vanuatu Vatu', exponent: 0 },
  XAF: { code: 'XAF', name: 'CFA franc BEAC', exponent: 0 },
  XCD: { code: 'XCD', name: 'East Caribbean Dollar', exponent: 2 },
  XOF: { code: 'XOF', name: 'CFA franc BCEAO', exponent: 0 },
  XPF: { code: 'XPF', name: 'CFP franc', exponent: 0 },
  YER: { code: 'YER', name: 'Yemeni Rial', exponent: 2 },
  ZAR: { code: 'ZAR', name: 'South African Rand', exponent: 2 },
  ZMW: { code: 'ZMW', name: 'Zambian Kwacha', exponent: 2 },
} as const satisfies Record<string, { code: string; name: string; exponent: number }>

/*
 * A list of all the currency codes supported by Razorpay.
 *
 * @see https://razorpay.com/docs/payments/international-payments#supported-currencies
 */
export const RAZORPAY_CURRENCY_CODES = [
  'AED',
  'ALL',
  'AMD',
  'AUD',
  'AWG',
  'AZN',
  'BAM',
  'BBD',
  'BDT',
  'BGN',
  'BHD',
  'BIF',
  'BMD',
  'BND',
  'BOB',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BZD',
  'CAD',
  'CHF',
  'CLP',
  'CNY',
  'COP',
  'CRC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ETB',
  'EUR',
  'FJD',
  'GBP',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HRK',
  'HTG',
  'HUF',
  'IDR',
  'ILS',
  'INR',
  'IQD',
  'ISK',
  'JMD',
  'JOD',
  'JPY',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KRW',
  'KWD',
  'KYD',
  'KZT',
  'LAK',
  'LKR',
  'LRD',
  'LSL',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MYR',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'OMR',
  'PEN',
  'PGK',
  'PHP',
  'PKR',
  'PLN',
  'PYG',
  'QAR',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SAR',
  'SCR',
  'SEK',
  'SGD',
  'SLL',
  'SOS',
  'SVC',
  'SZL',
  'THB',
  'TND',
  'TRY',
  'TTD',
  'TWD',
  'TZS',
  'UAH',
  'UGX',
  'USD',
  'UYU',
  'UZS',
  'VND',
  'VUV',
  'XAF',
  'XCD',
  'XOF',
  'XPF',
  'YER',
  'ZAR',
  'ZMW',
] as const

// Type-level assertion that the RAZORPAY_CURRENCY_CODES array matches the keys of the RAZORPAY_CURRENCIES object.
type _assert = Expect<
  Equal<keyof typeof RAZORPAY_CURRENCIES, typeof RAZORPAY_CURRENCY_CODES[number]>
>
